### ISSUE TITLE
[Bugs] multiple errors on retail

### ISSUE THREAD

**Issue by EKE00372** [ZeChrales/AllTheMogs#1]
Model missing with error, happened when player is void elf, pandaren, goblin....etc.
`Interface/AddOns/AllTheMogs/AppearanceModelFrame.lua:168: attempt to index field '?' (a nil value)`
![image](https://github.com/ZeChrales/AllTheMogs/assets/1412472/7c8e4596-2795-4887-8d7d-03af73b038fc)
model position incorrect when player is gnome without error
![image](https://github.com/ZeChrales/AllTheMogs/assets/1412472/1ff0785b-9373-4a7e-967d-4f68ef37e3a9)

Error happened when try browse fishing poles
`Interface/AddOns/AllTheMogs/AppearanceModelFrame.lua:321: attempt to get length of local 'listAppearances' (a nil value)`

Error happened when enable AllTheMogs and another addon useing LibUIDropDownMenu, and the DropdownMenu in AllTheMogs will be unusalbe. I guess because the lib include in AllTheMogs is earlier version so they conflict.
`LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)`

**Comment by ZeChrales** [comment]
Hey thanks a lot for this feedback, I don't test a lot on retail.
- I added some placeholders for retail races (everything after wotlk), I'll improve it later.
- I fixed exception on fishing poles, they are broken on retail for now.
- I could not reproduce dropdown issue, can you share your addon list ? or maybe try with only AllTheMogs activated.

**Comment by EKE00372** [comment]
> * I could not reproduce dropdown issue, can you share your addon list ? or maybe try with only AllTheMogs activated.

It's an conflict so it won't happened when only AllTheMogs activated.

Sorry for didn't express clearly, for exameple, Angrykeystones enable with AllTheMogs, Angrykeystones will get that error and AllTheMogs dropdown list will broke.
Already test with only both addon enable.

I've compare the lib and guess LibUIDropDownMenu in AllTheMogs is an earlier version missing `NewFeature` for retail.

**Comment by ZeChrales** [comment]
I updated LibUIDropDownMenu lib to latest version, but the problem in this case is that Angrykeystones is not registering the lib correctly. Anyway it should be OK now !

**Comment by EKE00372** [comment]
Errors are gone, but still have an issue:

model position incorrect when player is void elf, pandaren, goblin, evoker...etc, I guess all race not include in classic have same issue.
